# Generated by Django 4.0.2 on 2022-02-13 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('capacity', models.IntegerField(default=1, verbose_name='Вместительность')),
            ],
            options={
                'verbose_name': 'Переговорная комната',
                'verbose_name_plural': 'Переговорные комнаты',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_begin', models.DateTimeField(max_length=255, verbose_name='Дата начала')),
                ('datetime_end', models.DateTimeField(max_length=255, verbose_name='Дата окончания')),
                ('meeting_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_booking.meetingroom')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
    ]
